### PR TITLE
Feat: support k-quants q2_k

### PR DESCRIPTION
**Pull request by AuruTus**
Still in working. (Some common constants and helper functions for K-Quants are in `qkk` mod)
 
Ref: #76 #75

### CODE REVIEW

**Comment by AuruTus** [comment]
I'm not sure if other ways to find the nearest integer would work the same as llamma.cpp 's version, so I just copy those snippets and keep tests with some random floats generated in cpp code.

**Comment by flaneur2020** [comment]
> I'm not sure if other ways to find the nearest integer would work the same as llamma.cpp 's version, so I just copy those snippets and keep tests with some random floats generated in cpp code.

Don't worry, an end-to-end test using Q2_K can finally help us determine whether it works or not. We can find a model like this one: 

https://huggingface.co/jartine/TinyLlama-1.1B-Chat-v1.0-GGUF/blob/d3f63b09fb8b2a1fda466efd1705c103ba3cb5aa/TinyLlama-1.1B-Chat-v1.0.Q2_K.gguf

**Comment by AuruTus** [comment]
The q2k dequantization has a diff error which llama.cpp also has. I just ignore it for now. Will try a model later.

**Comment by flaneur2020** [comment]
thank you for your contribution! 

it appears that there are some merge conflicts that need to be resolved before merging.

**Comment by PsiACE** [comment]
I think it may be necessary to do a rebase. Currently, this commit has mixed many commits and files by others.

**Comment by AuruTus** [comment]
> I think it may be necessary to do a rebase. Currently, this commit has mixed many commits and files by others.

Alr done with rebase now. I incorrectly changed the code base before.

**Comment by flaneur2020** [comment]
cool, LGTM :+1:

**Comment by PsiACE** [comment]
Hi, @AuruTus ，I carefully examined your data generation method, and the diff error is caused by the data generation.

**Comment by PsiACE** [comment]
> Hi, @AuruTus ，I carefully examined your data generation method, and the diff error is caused by the data generation.

Please ignore me, I made a mistake

**Pull request merged**
