### PR TITLE
refactor: Split arch related code into seperate files

### PR DESCRIPTION
**Pull request by Xuanwo**

### CODE REVIEW

**Comment by flaneur2020** [comment]
i'd prefer delay this split, as there will be plenty amount of quantization formats, it'd better to keep the related logics in a single file

**Comment by Xuanwo** [comment]
How about organizing them in internal mod?

**Comment by flaneur2020** [comment]
by unifying the same logics in a same file, IMHO it'd be easier to test and change together. and when we introduce new quantization format, just adding one file is ok, without need to change other files.

I guess we can take an approach like try reduce the platform related code by utilizing stdsimd or auto vectorization on not that performance critical operations like `quantize` and `dequantize`, and only use the platform related code on performance critical `vec_dot` to havest all the performance potential, thus may reduce the burden on maintaining the platform differences.

**Comment by Xuanwo** [comment]
> by unifying the same logics in a same file, IMHO it'd be easier to test and change together. and when we're introducing new quantization format, just adding one file is ok, without need to change other files.

There is a misunderstanding here. My new approach is to have something like

```
fn vec_dot() {}

mod x86_64_avx2 {
  fn vec_dot()
}

mod aarch64_neon {
  fn vev_dot()
}
```

They are still in the same file, but organized by mod.

What do you think?

**Comment by flaneur2020** [comment]
> > by unifying the same logics in a same file, IMHO it'd be easier to test and change together. and when we're introducing new quantization format, just adding one file is ok, without need to change other files.
> 
> There is a misunderstanding here. My new approach is to have something like
> 
> ```
> fn vec_dot() {}
> 
> mod x86_64_avx2 {
>   fn vec_dot()
> }
> 
> mod aarch64_neon {
>   fn vev_dot()
> }
> ```
> 
> They are still in the same file, but organized by mod.
> 
> What do you think?

looks fine to me! 

this style can both help reducing platform branches with dirty macros while allowing us edit few files as possible when we're adding new things. :+1:

**Comment by Xuanwo** [comment]
> looks fine to me!

Let me do this.

**Comment by Xuanwo** [comment]
cc @flaneur2020, please review again.

**Review by flaneur2020 — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
